- name: Installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Remove default directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download & Unzip frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Setup reverse proxy
  ansible.builtin.template:
    src: frontend.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes