- name: Add App user
  ansible.builtin.shell: useradd roboshop

- name: Remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download & Unzip app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/${component}.zip
    dest: /app
    remote_src: yes
