- name: Setup mongodb repo
  ansible.builtin.template:
    src: mongo.repo
    dst: etc/yum.repos.d/mongo.repo

- name: Install mongodb client
  ansible.builtin.dnf:
    name: mongodb-org-shell
    state: installed

- name: Load schema
  ansible.builtin.shell: mongo --host mongodb-dev.smitdevops.online </app/schema/ {{component}}.js

